### PR TITLE
Fix OpenGraph image

### PR DESCRIPTION
**Pull request by Jolg42**
It would be great if we could merge https://github.com/xHain-hackspace/xhain-website/pull/18
So we can test this on the preview deployment with https://metatags.io/
I managed to use Ngrok for having a preview:

See now with this PR changes:
German
Screenshot 2023-07-02 at 16 37 44
English
Screenshot 2023-07-02 at 16 37 31

### CODE REVIEW

**Comment by gueldenstone** [comment]
I have merged #18 please rebase and try it out :)

**Comment by Jolg42** [comment]
@gueldenstone It works ✨ 
Screenshot 2023-07-03 at 09 54 26
Screenshot 2023-07-03 at 09 54 38

**Review by gueldenstone — APPROVED** [review]

**Comment by gueldenstone** [comment]
Awesome! You should be able to merge.

**Comment by Jolg42** [comment]
@gueldenstone Thanks! It looks like I don't have "write access" yet and can't merge at the moment, see
Screenshot 2023-07-03 at 10 01 43

**Pull request merged**
