### PR TITLE
Add Surge preview

### PR DESCRIPTION
**Pull request by gueldenstone**

### CODE REVIEW

**Review by pantierra — APPROVED** [review]
Oh, wow! Awesome, that was fast and works. Very cool!
You may want to adjust the readme file, to explain what is happening with this.

I made `main` the default branch again.

**Comment by xamanu** [comment]
I made `main` the default branch again.

**Comment by Jolg42** [comment]
@gueldenstone this looks like a great PR 🙌🏼 
Anything blocking the current PR? Just curious and happy to find this PR :)

**Comment by gueldenstone** [comment]
There is a problem with the hugo framework here. If you look closely, clicking on the link will redirect you to the actual xHain website and not the surge preview. I did not have time to further develop here. If you have capacity, feel free to improve!

**Comment by Jolg42** [comment]
Maybe it's not a blocker since these urls work as expected (only without lang it redirects to live website)
- https://xhain-hackspace-xhain-website-pr-18.surge.sh/en/
- https://xhain-hackspace-xhain-website-pr-18.surge.sh/de/

**Pull request merged**
