### PR TITLE
Add github action to download calendar data

### PR DESCRIPTION
**Pull request by jdwillemse**
I'm trying to remove the need for go processing on the Nextcloud calendar.

- This is done by running a Github workflow every hour (this is arbitrary and can by changed)
- The workflow fetches the latest calendar data
- The CalDav format, which is hard to use, is converted to key-value JSON 
- Modified data is saved to the data folder where it can be used in templates directly

The template update step is available for inspection in #62

### CODE REVIEW

**Comment by pantierra** [comment]
Awesome work! I love we rely on the jcal export and the hugo template engine to process the json.
But I am doubting we should save the changing data in the repo. Instead, I'd prefer to keep the build pipeline similar to what it is and replace `calendar_parse` with the download of the jcal and `jq`-conversion right before the hugo call. And please stay with `.woodpecker.yml`, which we prefer over github actions.

**Comment by jdwillemse** [comment]
> But I am doubting we should save the changing data in the repo

My thinking behind committing the export is as follows:
- Even though the cron job checks at regular intervals for changes to the calendar, a rebuild is only triggered when there is actually a change in the export that gets pushed to the repo.
- Devs who need to work on the calendar locally have no extra steps to set that up and get it working e.g. installing jq and running an export
- Having data in the repo is the canonical way to use Hugo and for all other content this is how we handle it.
- I can't see any downside to having this file committed. It is no especially big and it is a single file

**Comment by jdwillemse** [comment]
I'm happy for the CI to move to Woodpecker but it is a tool that I have never worked with. Any help on this front would be appreciated

**Comment by pantierra** [comment]
Rerolled this PR and adjusted slightly in #63.

**Pull request closed without merging**
