### PR TITLE
add new calendar

### PR DESCRIPTION
**Pull request by mrhide-de**

### CODE REVIEW

**Comment by pantierra** [comment]
A very basic integration is working!

But a lot of things todo.

**Comment by pantierra** [comment]
Minimal viable product is working. Now we can add the nice features one by one.

**Comment by pantierra** [comment]
@gueldenstone Is it possible to run the CI once per night? So to fetch the new calendar infos.

**Comment by gueldenstone** [comment]
> @gueldenstone Is it possible to run the CI once per night? So to fetch the new calendar infos.

Should be possible. I'll tweak the main's ci-config so you can rebase.

**Comment by gueldenstone** [comment]
@xamanu  The Rendering of the descriptions seems off. Newlines are not being rendered properly (see Godot Event)

**Comment by pantierra** [comment]
Thanks for checking and reporting, @gueldenstone! I fixed it.

**Review by pantierra — APPROVED** [review]

**Pull request merged**
