### PR TITLE
fix: remove event highlighting

### PR DESCRIPTION
**Pull request by jdwillemse**
Events, once marked as active, do not update to become inactive when they are done. I've updated the script to check again at the end of the event.

I've also added polling to check every 10 minutes to see if there is an active event.

I updated the active event animation in order to keep the event details legible. The previous opacity animation reduced readability during part of the animation. The animation I implemented is quite a departure from the previous one so if someone wan't to change this or suggest something subtler, please go ahead.

### CODE REVIEW

**Comment by xamanu** [comment]
Love it. Many thanks.

**Review by pantierra — APPROVED** [review]
Love it. Many thanks.

**Comment by gueldenstone** [comment]
Seems broken now on mobile for me. No scroll to current day and I can not open the details of a event. 

Tested with firefox on iOS.

**Comment by pantierra** [comment]
I tested, and checked again, and I don't have any issues. Are you coming tomorrow and can you show me?

**Comment by gueldenstone** [comment]
Im not in Berlin today but here is a screen recording: https://github.com/xHain-hackspace/xhain-website/assets/45048474/1f6a6785-2066-4bfd-95d1-5eb469c511b4

**Pull request merged**
